Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine317"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 2048
    virtualbox.cpus = 2
  end

  config.vm.define "yforeauS" do |server|
    server.vm.hostname = "yforeauS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant"
    server.vm.provision "shell", privileged: true, path: "scripts/k3s-server.sh", args: ["192.168.56.110"]
  end
end