apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: playground-argocd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kibotrel/kibotrel-iot-part-3
    targetRevision: HEAD
    path: app
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      selfHeal: true
      prune: true