Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine317"

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.memory = 1024
    virtualbox.cpus = 1
  end

  config.vm.define "kibotrelS" do |server|
    server.vm.hostname = "kibotrelS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.synced_folder ".", "/vagrant"
    server.vm.provision "shell", privileged: true, path: "scripts/k3s-server.sh", args: ["192.168.56.110"]
  end

  config.vm.define "kibotrelSW" do |worker|
    worker.vm.hostname = "kibotrelSW"
    worker.vm.network "private_network", ip: "192.168.56.111"
    worker.vm.synced_folder ".", "/vagrant"
    worker.vm.provision "shell", privileged: true, path: "scripts/k3s-worker.sh", args: ["192.168.56.110", "192.168.56.111"]
  end
end